### ISSUE TITLE
Missing Country

### ISSUE THREAD

**Issue by alanj1998** [ShaneMcGowan/list-of-all-countries-2019-html-json#1]
Dear Author,

You forgot some UN recognised countries like Kosovo. 

Kind Regards,
Alanj1998

**Comment by ShaneMcGowan** [comment]
Dear @alanj1998 

I apologise for this error, Please create a pull request updating both the json and the html file.
Please also update the readme with your sources for what "is and isn't acountry" 

Big Kiss,
Shane

**Comment by alanj1998** [comment]
Please see #2

**Comment by ShaneMcGowan** [comment]
Closing due to lack of information regarding Kosovo's recognition as a country

**Comment by dairefinn** [comment]
https://www.scp-ks.org/en

**Comment by ShaneMcGowan** [comment]
> https://www.scp-ks.org/en
> https://www.bbc.com/news/world-europe-12006948
> https://en.wikipedia.org/wiki/Kosovo
> I think you'll find Kosovo is a country

The information you have provided states that the current status of Kosovo is Disputed

**Comment by alanj1998** [comment]
> > https://www.scp-ks.org/en
> > https://www.bbc.com/news/world-europe-12006948
> > https://en.wikipedia.org/wiki/Kosovo
> > I think you'll find Kosovo is a country
> 
> The information you have provided states that the current status of Kosovo is Disputed

The current validity of this list is disputed therefore OP should look into proving that Kosovo is not a valid country.

**Comment by alanj1998** [comment]
Duplicate of #2.

**Comment by ShaneMcGowan** [comment]
> > > https://www.scp-ks.org/en
> > > https://www.bbc.com/news/world-europe-12006948
> > > https://en.wikipedia.org/wiki/Kosovo
> > > I think you'll find Kosovo is a country
> > 
> > 
> > The information you have provided states that the current status of Kosovo is Disputed
> 
> The current validity of this list is disputed therefore OP should look into proving that Kosovo is not a valid country.

I don't have the authority to declare what is and is not a country. Not anymore...
